add support for apiOptions - language & region
Tintef/react-google-places-autocomplete pull request #148
Opened 2021-02-17 16:57 UTC by bogdanbalc

2021-02-18 01:25 UTC, Tintef requested changes
Looks good, thanks @bogdanbalc 

One more request, can you please remove all the automatic formatting you added?
-- Mostly for tracking purposes (git blame)

2021-02-18 01:25 UTC, Tintef commented on docs/docs/props.md
> +Autocompletion request object to add restrictions to the search. Let's see the shape this prop can take:
Can you update this text so it's not the same as the other prop?

Maybe something like this:
```suggestion
Object to configure the google script to inject. Let's see the shape this prop can take:
```

2021-02-18 01:25 UTC, Tintef commented on src/helpers/injectScript.ts
> +  }, '');
wdyt about this:
```suggestion
  const options = Object.entries(apiOptions).reduce((acc, [key, value) => `${acc}&${key}=${value}`, '');
```

2021-02-18 15:59 UTC, Tintef approved these changes
@bogdanbalc This looks great! Just one minor nitpick 😅 

I'll release this over the weekend

2021-02-18 15:59 UTC, Tintef commented on docs/docs/props.md
> +/>
What do you think about adding `apiKey` here? So it's more explicit that this will only work if the apiKey prop is passed as well
```suggestion
<GooglePlacesAutocomplete
  apiKey="***************"
  apiOptions={{ language: 'fr', region: 'fr' }}
/>
```

2021-02-18 16:34 UTC, bogdanbalc commented
> @bogdanbalc This looks great! Just one minor nitpick 😅
> 
> I'll release this over the weekend

That would be great. Thanks!

2021-02-21 00:52 UTC, merged

2021-11-21 23:03 UTC, simplenotezy commented
Hey! This is really awesome, thanks @bogdanbalc. Is this released to npm yet?